"""message添加status字段

Revision ID: 32fcc8477ded
Revises: 5e2f53fb5022
Create Date: 2026-10-05 21:17:21.447624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fcc8477ded'
down_revision: Union[str, Sequence[str], None] = '5e2f53fb5022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'status')
    # ### end Alembic commands ###
