"""message表更新错误码，错误信息字段

Revision ID: af727a59ca27
Revises: a6f3c912b840
Create Date: 2026-10-07 23:44:21.302583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af727a59ca27'
down_revision: Union[str, Sequence[str], None] = 'a6f3c912b840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('error_code', sa.String(length=64), nullable=False))
    op.add_column('message', sa.Column('error_message', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'error_message')
    op.drop_column('message', 'error_code')
    # ### end Alembic commands ###
